# Site settings
title: JustWe!!!
email: hyv.zero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  programming, game developer, and everything of cool & fun.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hywei
github_username:  hywei

# Build settings
markdown: kramdown
